# a variable named `cutoff` is required by GROMOS_54A7_ATB.lt
variable cutoff equal 14.0 # Angstroms
boundary p p p
units real
atom_style      full
bond_style      harmonic
angle_style     harmonic
dihedral_style  harmonic
improper_style  harmonic
#pair_style      lj/cut/coul/cut ${cutoff}  # for non-period sims
pair_style      lj/cut/coul/long   ${cutoff}
kspace_style    pppm 0.0001
special_bonds lj 0.0 0.0 0.5 coul 0.0 0.0 1.0 angle yes dihedral yes
