name: Deploy GitHub Pages

on:
  push:
    branches:
      - 2Aug2023
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          context: .
          submodules: true 
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          context: .
          python-version: 3.9
      - name: Install sphinx
        run: |
          pip install sphinx
          pip install furo
          pip install sphinx-togglebutton
          pip install pygments-lammps
          pip install sphinx-favicon
          pip install sphinxcontrib.bibtex
          pip install sphinx-tabs
      - name: Build
        run: |
          cd docs/sphinx/
          make clean
          make html
          cp source/index_replace.html build/html/index.html
          cp source/gromacs_replace.html build/html/miscellaneous/use-gromacs-instead.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/2Aug2023' }}
        with:
          context: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/
